config/routes.rb
Rails.application.routes.draw do

  root 'places#index'

  resources :places do
    resources :carts do
      resources :cart_items
    end  
  end

  ActiveAdmin.routes(self)
  devise_for :users

  

end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter
	def authorized?(action, subject = nil)
		user.admin?
	end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :user
	belongs_to :place
	
	has_many :cart_items
	has_many :dishes, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
	belongs_to :dish
	belongs_to :cart
end

app/models/dish.rb
class Dish < ActiveRecord::Base
	belongs_to :place

	has_many :cart_items
	has_many :carts, through: :cart_items

	
	validates :title, presence: true, 
				length: {maximum: 50}

	validates :description, length: {maximum: 250}

	validates :price, presence: true,
			   numericality: { greater_than_or_equal: 0 }

	has_attached_file :image,
				styles: {medium: '200x200>', thumb: '120x120>'},
				default_url: 'images/:style/missing.png'

	validates_attachment :image,
				content_type: {content_type: %w(image/jpg image/png image/gif) }
end

app/models/place.rb
class Place < ActiveRecord::Base
	has_many :carts
	has_many :dishes

	has_attached_file :image,
				styles: {medium: '200x200>', thumb: '120x120>'},
				default_url: 'images/styles:/missing.png'
	validates_attachment_content_type :image,
				content_type: ['image/jpg', 'image/png', 'image/gif']

	validates :title, presence: true, length: {maximum: 50}
	validates :description, length: {maximum: 250}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :name, presence: true,
					 length: { maximum: 50}

  validates :email, presence: true

  has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def access_denied(exception)
  	flash[:danger] = exception.message
  	redirect_to root_url
  end

  private 

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :address]) 
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone, :address])  	
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
	def new
		@cart_item = Cart_item.new
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def new
		@cart = Cart.new
	end

	def show
		@cart = Cart.find(params[:id])

		@cart_sum = calculate_cart(@cart)
	end

	def create
		@place = Place.find(params[:place_id])
    	@cart = @place.carts.create(cart_params) 

		respond_to do |format|
			format.html {redirect_to @place}
			format.js {}
			format.json {render json: @cart, status: :created}
		end
		
	end

	def destroy
		@place = Place.find(params[:place_id])
    	@cart = Cart.find(params[:id])
	    @cart.destroy

    respond_to do |format|
      # format.html { redirect_to @cart }
      format.json { head :no_content }
      format.js   {}
    end
  end

  private 

  def cart_params
  	params.require(:cart).permit(:place_id, :user_id)
  end

  def calculate_cart(cart)
  	total_sum = 0
  	cart.cart_items.each do |item|
  		sub_total = 0
  		item.each do |good|
  			sub_total += good.dish.price * good.number
  		end
  		total_sum += sub_total
  	end
  	return total_sum
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	def index
		@places = Place.all
	end

	def show
		@place = Place.find(params[:id])
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/carts/_cart.html.erb
<li>
  <p>
    <strong> #<%= @cart.id %> заказа: </strong>
    <% for item in @cart.cart_items %>
    	<%= item.dish.title %>
    	<%= item.dish.price %>
    	<%= item.number %>
  </p>

  <p>
    <%= link_to 'Удалить блюдо', place_carts_path(@place.id), method: :delete, class: "cart-delete", remote: true %>
  </p>
  <% end %>
</li>
<li>
	<strong> Сумма заказа: @cart_sum </strong>
</li>
<li>
	<%= link_to "Удалить заказ", place_carts_path(@card), method: :delete %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodtracktor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/application/navbar' %>

	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>">
				<%= value %>
			</div>
		<% end %>
	</div>

	<%= yield :top_content %>

	<div class="container">
		<h1><%= yield :header %></h1>

		<%= yield %>
	</div>

</body>
</html>

app/views/layouts/application/_navbar.html.erb
 <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#foodtracker-collapsed-navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "FoodTracktor", root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="foodtracker-collapsed-navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            Hello,<%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
          </p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <li><a href="#">View orders</a></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>

          <% if current_user.admin? %>
            <p class="navbar-text">
              <%= link_to "Admin Panel", admin_root_path, class: "navbar-link" %>
            </p>
          <% end %>

        <% else %>
          <li><%= link_to new_user_registration_path do %> 
            <span class="glyphicon glyphicon-user"></span> Sign Up
            <% end %>
          </li>
          <li><%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in" %></span> Login
            <% end %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/places/_show.html.erb
<div class="row">

	<div class="col-md-10 col-sm-10">
		<div class="place_details">
			<div class="place_title"><%= @place.title %></div>
			<div class="place_picture"><%= image_tag @place.image.url(:medium) %></div>
			<div class="place_description"><%= @place.description %></div>
		</div>	

	  <% "Список блюд" %>
		
			<% @place.dishes.each do |dish| %>

			
					<div class="col-md-6 col-sm-6">
						<div class="dish">
							<div class="dish-cell">
								<div class="dish-image"> <%= image_tag dish.image.url(:medium), class: "img-circle" %>
								</div>

								<div class="dish-description"> 
									<div class="dish-title"><%= dish.title %></div>
									<div class="dish-description-body"><%= dish.description %></div>
								</div>
							</div>

							<div class="dish-divider"></div>

							<div class="dish-bottom">
								
								<div class="dish-price"><%= dish.price %> сом</div>
								<%= form_for @cart, remote: true do |f| %>	
									<div class="dish-quantity" id="dish-quantity">
										<%= f.hidden_field :place_id, value: dish.place_id %>
										<%= f.hidden_field :dish_id, value: dish.id %>
										<%= f.label :number_dishes, 'К-во' %>
										<%= f.text_field :number_dishes, value: '1', style: 'width:30px;' %>
									</div>
									<div class="dish-order-btn"><%= f.submit 'Заказать', id: 'btn-order', class: "btn btn-primary" %>
									</div>
								<% end %>	
							</div>	

						</div>
					</div>	
				
			<% end %>
		</div>

	<div class="col-md-2 col-sm-2 cart-col">
		<div class="user_cart" id="user_cart"> Ваш заказ:
			<section id="cart-section">
			  <ol id="yourcart">
			  </ol>
			</section>
		</div> 
	</div>
</div>

app/views/places/index.html.erb
<h2>Все заведения</h2>

<div class="row">
	<% @places.each do |place| %>
		<div class="col-md-3 col-sm-6">
			<div class="caffee">
				<p><%= image_tag place.image.url(:medium) %></p>
				<p><%= link_to place.title, place_path(place.id) %></p>
			</div>	
		</div>
	<% end %>
</div>

app/views/places/show.html.erb
<div class="row">
	<% @cart = Cart.new %>
	<div class="col-md-10 col-sm-10">
		<div class="place_details">
			<div class="place_title"><%= @place.title %></div>
			<div class="place_picture"><%= image_tag @place.image.url(:thumb) %></div>
			<div class="place_description"><%= @place.description %></div>
		</div>	

	  <% "Список блюд" %>
		<div class="col-md-10 col-sm-10">
			<div class="cafe_category">
				<h3>Список блюд</h3>
			</div>
			<% @place.dishes.each do |dish| %>

			
					<div class="col-md-6 col-sm-6">
						<div class="dish">
							<div class="dish-cell">
								<div class="dish-image"> <%= image_tag dish.image.url(:medium), class: "img-circle" %>
								</div>

								<div class="dish-description"> 
									<div class="dish-title"><%= dish.title %></div>
									<div class="dish-description-body"><%= dish.description %></div>
								</div>
							</div>

							<div class="dish-divider"></div>

							<div class="dish-bottom">
								
								<div class="dish-price"><%= dish.price %> сом</div>

								<%= form_for [@place, @cart] do |f| %>	
									<div class="dish-quantity" id="dish-quantity">
										<%= f.hidden_field :place_id, value: dish.place_id %>
										<%= f.hidden_field :dish_id, value: dish.id %>
										<%= f.label :number_dishes, 'К-во' %>
										<%= f.text_field :number_dishes, value: '1', style: 'width:30px;' %>
									</div>
									<div class="dish-order-btn"><%= f.submit 'Заказать', id: 'btn-order', class: "btn btn-primary" %>
									</div>
								<% end %>	
							</div>	

						</div>
					</div>	
				
			<% end %>
		</div>
	</div>
		
	<div class="col-md-2 col-sm-2 cart-col">
		<div class="user_cart" id="user_cart"> Ваш заказ:
			<section id="cart-section">
			  <ol id="yourcart">
			  </ol>
			</section>
		</div> 
	</div>
</div>